<?php return array(
    'root' => array(
        'name' => 'codeigniter4/appstarter',
        'pretty_version' => 'v4.4.5',
        'version' => '4.4.5.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'codeigniter4/appstarter' => array(
            'pretty_version' => 'v4.4.5',
            'version' => '4.4.5.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeigniter4/framework' => array(
            'pretty_version' => 'v4.4.5',
            'version' => '4.4.5.0',
            'reference' => 'f5844cb9790d87ff6043203953821740ba3aa592',
            'type' => 'project',
            'install_path' => __DIR__ . '/../codeigniter4/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => 'af459883f4018d0f8a0c69c7a209daef3bf973ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
